version: 2

project_name: apx

before:
  hooks:
    - mise test

builds:
  - id: apx
    main: ./cmd/apx
    binary: apx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

brews:
  - name: apx
    description: "CLI wrapper for platform-specific sandboxes"
    homepage: "https://github.com/UsingCoding/apx"
    license: "MIT"
    repository:
      owner: UsingCoding
      name: homebrew-public
    dependencies:
      - name: go
        type: build
    install: |
      ldflags = %W[
        -s -w
        -X main.version=#{version}
        -X main.commit=homebrew
      ]
      system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"apx"), "./cmd/apx"

archives:
  - files:
      - LICENSE*
      - README*
      - go.mod
      - go.sum
      - cmd/**
      - internal/**
      - registry/**
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^version-increment:'

release:
  github:
    owner: UsingCoding
    name: apx
